const express = require('express');
const router = express.Router();

// AUTO-GENERATED STUB ROUTES - returns 501 Not Implemented
// Generated by scripts/create-stubs.js

router.all('/abha/status/:param', (req, res) => {
  console.warn('Stub hit:', req.method, req.originalUrl);
  res.status(501).json({ error: 'Not implemented (auto-stub)', path: req.originalUrl });
});

router.all('/allergies/:param', (req, res) => {
  console.warn('Stub hit:', req.method, req.originalUrl);
  res.status(501).json({ error: 'Not implemented (auto-stub)', path: req.originalUrl });
});

router.all('/appointment-intents/:param', (req, res) => {
  console.warn('Stub hit:', req.method, req.originalUrl);
  res.status(501).json({ error: 'Not implemented (auto-stub)', path: req.originalUrl });
});

router.all('/appointment-intents/:param/status', (req, res) => {
  console.warn('Stub hit:', req.method, req.originalUrl);
  res.status(501).json({ error: 'Not implemented (auto-stub)', path: req.originalUrl });
});

router.all('/appointment-intents/:param/convert', (req, res) => {
  console.warn('Stub hit:', req.method, req.originalUrl);
  res.status(501).json({ error: 'Not implemented (auto-stub)', path: req.originalUrl });
});

router.all('/appointments/:param', (req, res) => {
  console.warn('Stub hit:', req.method, req.originalUrl);
  res.status(501).json({ error: 'Not implemented (auto-stub)', path: req.originalUrl });
});

router.all('/appointments/:param/payment', (req, res) => {
  console.warn('Stub hit:', req.method, req.originalUrl);
  res.status(501).json({ error: 'Not implemented (auto-stub)', path: req.originalUrl });
});

router.all('/appointments/:param/status', (req, res) => {
  console.warn('Stub hit:', req.method, req.originalUrl);
  res.status(501).json({ error: 'Not implemented (auto-stub)', path: req.originalUrl });
});

router.all('/backup/:param', (req, res) => {
  console.warn('Stub hit:', req.method, req.originalUrl);
  res.status(501).json({ error: 'Not implemented (auto-stub)', path: req.originalUrl });
});

router.all('/backup/download/:param', (req, res) => {
  console.warn('Stub hit:', req.method, req.originalUrl);
  res.status(501).json({ error: 'Not implemented (auto-stub)', path: req.originalUrl });
});

router.all('/bills/:param/status', (req, res) => {
  console.warn('Stub hit:', req.method, req.originalUrl);
  res.status(501).json({ error: 'Not implemented (auto-stub)', path: req.originalUrl });
});

router.all('/bills/:param', (req, res) => {
  console.warn('Stub hit:', req.method, req.originalUrl);
  res.status(501).json({ error: 'Not implemented (auto-stub)', path: req.originalUrl });
});

router.all('/bills/:param/pdf', (req, res) => {
  console.warn('Stub hit:', req.method, req.originalUrl);
  res.status(501).json({ error: 'Not implemented (auto-stub)', path: req.originalUrl });
});

router.all('/bills/:param/whatsapp', (req, res) => {
  console.warn('Stub hit:', req.method, req.originalUrl);
  res.status(501).json({ error: 'Not implemented (auto-stub)', path: req.originalUrl });
});

router.all('/bills/pdf/:param', (req, res) => {
  console.warn('Stub hit:', req.method, req.originalUrl);
  res.status(501).json({ error: 'Not implemented (auto-stub)', path: req.originalUrl });
});

router.all('/clinics/:param', (req, res) => {
  console.warn('Stub hit:', req.method, req.originalUrl);
  res.status(501).json({ error: 'Not implemented (auto-stub)', path: req.originalUrl });
});

router.all('/diagnosis-templates/:param', (req, res) => {
  console.warn('Stub hit:', req.method, req.originalUrl);
  res.status(501).json({ error: 'Not implemented (auto-stub)', path: req.originalUrl });
});

router.all('/doctor-availability/:param/availability', (req, res) => {
  console.warn('Stub hit:', req.method, req.originalUrl);
  res.status(501).json({ error: 'Not implemented (auto-stub)', path: req.originalUrl });
});

router.all('/doctor-availability/:param/slots', (req, res) => {
  console.warn('Stub hit:', req.method, req.originalUrl);
  res.status(501).json({ error: 'Not implemented (auto-stub)', path: req.originalUrl });
});

router.all('/doctor-availability/:param/slots/:slot', (req, res) => {
  console.warn('Stub hit:', req.method, req.originalUrl);
  res.status(501).json({ error: 'Not implemented (auto-stub)', path: req.originalUrl });
});

router.all('/doctors/:param', (req, res) => {
  console.warn('Stub hit:', req.method, req.originalUrl);
  res.status(501).json({ error: 'Not implemented (auto-stub)', path: req.originalUrl });
});

router.all('/doctors/by-user/:param', (req, res) => {
  console.warn('Stub hit:', req.method, req.originalUrl);
  res.status(501).json({ error: 'Not implemented (auto-stub)', path: req.originalUrl });
});

router.all('/family-history/:param', (req, res) => {
  console.warn('Stub hit:', req.method, req.originalUrl);
  res.status(501).json({ error: 'Not implemented (auto-stub)', path: req.originalUrl });
});

router.all('/injection-templates/:param', (req, res) => {
  console.warn('Stub hit:', req.method, req.originalUrl);
  res.status(501).json({ error: 'Not implemented (auto-stub)', path: req.originalUrl });
});

router.all('/injection-templates/:param/use', (req, res) => {
  console.warn('Stub hit:', req.method, req.originalUrl);
  res.status(501).json({ error: 'Not implemented (auto-stub)', path: req.originalUrl });
});

router.all('/insurance/:param', (req, res) => {
  console.warn('Stub hit:', req.method, req.originalUrl);
  res.status(501).json({ error: 'Not implemented (auto-stub)', path: req.originalUrl });
});

router.all('/insurance/patient/:param', (req, res) => {
  console.warn('Stub hit:', req.method, req.originalUrl);
  res.status(501).json({ error: 'Not implemented (auto-stub)', path: req.originalUrl });
});

router.all('/lab-templates/:param', (req, res) => {
  console.warn('Stub hit:', req.method, req.originalUrl);
  res.status(501).json({ error: 'Not implemented (auto-stub)', path: req.originalUrl });
});

router.all('/labs/:param', (req, res) => {
  console.warn('Stub hit:', req.method, req.originalUrl);
  res.status(501).json({ error: 'Not implemented (auto-stub)', path: req.originalUrl });
});

router.all('/medical-certificates/:param', (req, res) => {
  console.warn('Stub hit:', req.method, req.originalUrl);
  res.status(501).json({ error: 'Not implemented (auto-stub)', path: req.originalUrl });
});

router.all('/medications-templates/:param', (req, res) => {
  console.warn('Stub hit:', req.method, req.originalUrl);
  res.status(501).json({ error: 'Not implemented (auto-stub)', path: req.originalUrl });
});

router.all('/notify/:param/read', (req, res) => {
  console.warn('Stub hit:', req.method, req.originalUrl);
  res.status(501).json({ error: 'Not implemented (auto-stub)', path: req.originalUrl });
});

router.all('/patient-data/labs/:id/reports/:reportId', (req, res) => {
  console.warn('Stub hit:', req.method, req.originalUrl);
  res.status(501).json({ error: 'Not implemented (auto-stub)', path: req.originalUrl });
});

router.all('/patient-data/records/:param', (req, res) => {
  console.warn('Stub hit:', req.method, req.originalUrl);
  res.status(501).json({ error: 'Not implemented (auto-stub)', path: req.originalUrl });
});

router.all('/patient-data/records/:id/history/:historyId', (req, res) => {
  console.warn('Stub hit:', req.method, req.originalUrl);
  res.status(501).json({ error: 'Not implemented (auto-stub)', path: req.originalUrl });
});

router.all('/patient-data/timeline/:id/event/:eventId', (req, res) => {
  console.warn('Stub hit:', req.method, req.originalUrl);
  res.status(501).json({ error: 'Not implemented (auto-stub)', path: req.originalUrl });
});

router.all('/patient-data/vitals/:param', (req, res) => {
  console.warn('Stub hit:', req.method, req.originalUrl);
  res.status(501).json({ error: 'Not implemented (auto-stub)', path: req.originalUrl });
});

router.all('/patient-data/vitals/:id/reading/:readingId', (req, res) => {
  console.warn('Stub hit:', req.method, req.originalUrl);
  res.status(501).json({ error: 'Not implemented (auto-stub)', path: req.originalUrl });
});

router.all('/patients/:param', (req, res) => {
  console.warn('Stub hit:', req.method, req.originalUrl);
  res.status(501).json({ error: 'Not implemented (auto-stub)', path: req.originalUrl });
});

router.all('/prescription-templates/:param', (req, res) => {
  console.warn('Stub hit:', req.method, req.originalUrl);
  res.status(501).json({ error: 'Not implemented (auto-stub)', path: req.originalUrl });
});

router.all('/prescriptions/:param', (req, res) => {
  console.warn('Stub hit:', req.method, req.originalUrl);
  res.status(501).json({ error: 'Not implemented (auto-stub)', path: req.originalUrl });
});

router.all('/prescriptions/detail/:param/diagnoses', (req, res) => {
  console.warn('Stub hit:', req.method, req.originalUrl);
  res.status(501).json({ error: 'Not implemented (auto-stub)', path: req.originalUrl });
});

router.all('/prescriptions/draft/:param', (req, res) => {
  console.warn('Stub hit:', req.method, req.originalUrl);
  res.status(501).json({ error: 'Not implemented (auto-stub)', path: req.originalUrl });
});

router.all('/prescriptions/patient/:param/last', (req, res) => {
  console.warn('Stub hit:', req.method, req.originalUrl);
  res.status(501).json({ error: 'Not implemented (auto-stub)', path: req.originalUrl });
});

router.all('/prescriptions/pdf/:param', (req, res) => {
  console.warn('Stub hit:', req.method, req.originalUrl);
  res.status(501).json({ error: 'Not implemented (auto-stub)', path: req.originalUrl });
});

router.all('/queue/:param/status', (req, res) => {
  console.warn('Stub hit:', req.method, req.originalUrl);
  res.status(501).json({ error: 'Not implemented (auto-stub)', path: req.originalUrl });
});

router.all('/receipt-templates/:param', (req, res) => {
  console.warn('Stub hit:', req.method, req.originalUrl);
  res.status(501).json({ error: 'Not implemented (auto-stub)', path: req.originalUrl });
});

router.all('/subscription-packages/:param', (req, res) => {
  console.warn('Stub hit:', req.method, req.originalUrl);
  res.status(501).json({ error: 'Not implemented (auto-stub)', path: req.originalUrl });
});

router.all('/symptoms-templates/:param', (req, res) => {
  console.warn('Stub hit:', req.method, req.originalUrl);
  res.status(501).json({ error: 'Not implemented (auto-stub)', path: req.originalUrl });
});

router.all('/users/:param', (req, res) => {
  console.warn('Stub hit:', req.method, req.originalUrl);
  res.status(501).json({ error: 'Not implemented (auto-stub)', path: req.originalUrl });
});

router.all('/vip-patients/:param', (req, res) => {
  console.warn('Stub hit:', req.method, req.originalUrl);
  res.status(501).json({ error: 'Not implemented (auto-stub)', path: req.originalUrl });
});

router.all('/vip-patients/:param/activity-logs', (req, res) => {
  console.warn('Stub hit:', req.method, req.originalUrl);
  res.status(501).json({ error: 'Not implemented (auto-stub)', path: req.originalUrl });
});

router.all('/vip-patients/:param/access-control', (req, res) => {
  console.warn('Stub hit:', req.method, req.originalUrl);
  res.status(501).json({ error: 'Not implemented (auto-stub)', path: req.originalUrl });
});

module.exports = router;